language: cpp
compiler: gcc

os: linux
addons:
      apt:
          sources:
              - ubuntu-toolchain-r-test
          packages:
              - g++-8
              - python3.7-dev

script:
    - export CC=gcc-8
    - export CXX=g++-8
    - cmake --version
    - cmake CMakeLists.txt
    - cmake  --build .

